eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8090
  
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot
        output:
          destination: learning-spring-boot
          group: comments
          content-type: application/json
# Read by Enreka, which replaced by domain name
  application:
    name: images
    
